lodgistics:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
  env_file:
    - .lodgistics.env
  stdin_open: true
  tty: true

#sidekiq:
#  build: .
#  command: sidekiq
#  volumes:
#    - .:/app
#  links:
#    - postgres
#    - redis
#  env_file:
#    - .lodgistics.env
#  stdin_open: true
#  tty: true

postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgrespwd
  volumes:
    - lodgistics-postgres:/var/lib/postgresql/data

redis:
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - lodgistics-redis:/var/lib/redis/data

